module.exports = {
  baidu: [
    { code: 'auto', name: '自动检测语言' },
    { code: 'zh', name: '简体中文' },
    { code: 'en', name: '英语' },
    { code: 'yue', name: '粤语' },
    { code: 'wyw', name: '文言文' },
    { code: 'jp', name: '日语' },
    { code: 'fra', name: '法语' },
    { code: 'spa', name: '西班牙语' },
    { code: 'th', name: '泰语' },
    { code: 'ara', name: '阿拉伯语' },
    { code: 'ru', name: '俄语' },
    { code: 'pt', name: '葡萄牙语' },
    { code: 'de', name: '德语' },
    { code: 'it', name: '意大利语' },
    { code: 'el', name: '希腊语' },
    { code: 'nl', name: '荷兰语' },
    { code: 'pl', name: '波兰语' },
    { code: 'bul', name: '保加利亚语' },
    { code: 'est', name: '爱沙尼亚语' },
    { code: 'dan', name: '丹麦语' },
    { code: 'fin', name: '芬兰语' },
    { code: 'cs', name: '捷克语' },
    { code: 'rom', name: '罗马尼亚语' },
    { code: 'slo', name: '斯洛文尼亚语' },
    { code: 'swe', name: '瑞典语' },
    { code: 'hu', name: '匈牙利语' },
    { code: 'cht', name: '繁体中文' },
    { code: 'vie', name: '越南语' }
  ],
  tencent: [
    { code: 'auto', name: '自动检测语言' },
    { code: 'zh', name: '简体中文' },
    { code: 'zh-TW', name: '繁体中文' },
    { code: 'en', name: '英语' },
    { code: 'ja', name: '日语' },
    { code: 'ko', name: '韩语' },
    { code: 'fr', name: '法语' },
    { code: 'es', name: '西班牙语' },
    { code: 'it', name: '意大利语' },
    { code: 'de', name: '德语' },
    { code: 'tr', name: '土耳其语' },
    { code: 'ru', name: '俄语' },
    { code: 'pt', name: '葡萄牙语' },
    { code: 'vi', name: '越南语' },
    { code: 'id', name: '印尼语' },
    { code: 'th', name: '泰语' },
    { code: 'ms', name: '马来西亚语' },
    { code: 'ar', name: '阿拉伯语' },
    { code: 'hi', name: '印地语' }
  ],
  xunfei: [
    { code: 'cn', name: '汉语普通话' },
    { code: 'en', name: '英语' },
    { code: 'ii', name: '彝语' },
    { code: 'yue', name: '广东话' },
    { code: 'ja', name: '日语' },
    { code: 'ru', name: '俄语' },
    { code: 'fr', name: '法语' },
    { code: 'es', name: '西班牙语' },
    { code: 'ar', name: '阿拉伯语' },
    { code: 'it', name: '意大利语' },
    { code: 'tr', name: '土耳其语' },
    { code: 'vi', name: '越南语' },
    { code: 'th', name: '泰语' },
    { code: 'ko', name: '韩语' },
    { code: 'de', name: '德语' },
    { code: 'kka', name: '哈萨克语' },
    { code: 'af', name: '南非荷兰语' },
    { code: 'am', name: '阿姆哈拉语' },
    { code: 'az', name: '阿塞拜疆语' },
    { code: 'bn', name: '孟加拉语' },
    { code: 'ca', name: '加泰罗尼亚语' },
    { code: 'cs', name: '捷克语' },
    { code: 'da', name: '丹麦语' },
    { code: 'el', name: '希腊语' },
    { code: 'fa', name: '波斯语' },
    { code: 'fi', name: '芬兰语' },
    { code: 'he', name: '希伯来语' },
    { code: 'hi', name: '印地语' },
    { code: 'hr', name: '克罗地亚语' },
    { code: 'hu', name: '匈牙利语' },
    { code: 'hy', name: '亚美尼亚语' },
    { code: 'id', name: '印尼语' },
    { code: 'is', name: '冰岛语' },
    { code: 'tl', name: '塔加路语（菲律宾）' },
    { code: 'ro', name: '罗马尼亚语' },
    { code: 'ka', name: '格鲁吉亚语' },
    { code: 'km', name: '高棉语' },
    { code: 'lo', name: '老挝语' },
    { code: 'lt', name: '立陶宛语' },
    { code: 'lv', name: '拉脱维亚语' },
    { code: 'ml', name: '马拉雅拉姆语' },
    { code: 'mr', name: '马拉地语' },
    { code: 'nb', name: '博克马尔挪威语' },
    { code: 'ne', name: '尼泊尔语' },
    { code: 'nl', name: '荷兰语' },
    { code: 'pl', name: '波兰语' },
    { code: 'pt', name: '葡萄牙语' },
    { code: 'si', name: '僧伽罗语' },
    { code: 'sk', name: '斯洛伐克语' },
    { code: 'sl', name: '斯洛文尼亚语' },
    { code: 'sr', name: '塞尔维亚语' },
    { code: 'su', name: '巽他语' },
    { code: 'sv', name: '瑞典语' },
    { code: 'sw', name: '斯瓦希里语' },
    { code: 'ta', name: '泰米尔语' },
    { code: 'te', name: '泰卢固语' },
    { code: 'jv', name: '爪哇语' },
    { code: 'ms', name: '马来语' },
    { code: 'uk', name: '乌克兰语' },
    { code: 'ur', name: '乌尔都语' },
    { code: 'zu', name: '南非祖鲁语' },
    { code: 'mn', name: '内蒙语' },
    { code: 'my', name: '缅甸语' },
    { code: 'nm', name: '外蒙语' },
    { code: 'ps', name: '普什图语' },
    { code: 'ha', name: '豪萨语' },
    { code: 'uz', name: '乌兹别克语' },
    { code: 'tk', name: '土库曼语' },
    { code: 'tg', name: '塔吉克语' },
    { code: 'bg', name: '保加利亚语' }
  ],
  youdao: [
    { name: '自动检测语言', code: 'auto' },
    { name: '简体中文', code: 'zh-CHS' },
    { name: '阿拉伯语', code: 'ar' },
    { name: '德语', code: 'de' },
    { name: '英语', code: 'en' },
    { name: '西班牙语', code: 'es' },
    { name: '法语', code: 'fr' },
    { name: '印地语', code: 'hi' },
    { name: '印度尼西亚语', code: 'id' },
    { name: '意大利语', code: 'it' },
    { name: '日语', code: 'ja' },
    { name: '韩语', code: 'ko' },
    { name: '荷兰语', code: 'nl' },
    { name: '葡萄牙语', code: 'pt' },
    { name: '俄语', code: 'ru' },
    { name: '泰语', code: 'th' },
    { name: '越南语', code: 'vi' },
    { name: '繁体中文', code: 'zh-CHT' },
    { name: '南非荷兰语', code: 'af' },
    { name: '阿姆哈拉语', code: 'am' },
    { name: '阿塞拜疆语', code: 'az' },
    { name: '白俄罗斯语', code: 'be' },
    { name: '保加利亚语', code: 'bg' },
    { name: '孟加拉语', code: 'bn' },
    { name: '波斯尼亚语', code: 'bs' },
    { name: '加泰隆语', code: 'ca' },
    { name: '宿务语', code: 'ceb' },
    { name: '科西嘉语', code: 'co' },
    { name: '捷克语', code: 'cs' },
    { name: '威尔士语', code: 'cy' },
    { name: '丹麦语', code: 'da' },
    { name: '希腊语', code: 'el' },
    { name: '世界语', code: 'eo' },
    { name: '爱沙尼亚语', code: 'et' },
    { name: '巴斯克语', code: 'eu' },
    { name: '波斯语', code: 'fa' },
    { name: '芬兰语', code: 'fi' },
    { name: '斐济语', code: 'fj' },
    { name: '弗里西语', code: 'fy' },
    { name: '爱尔兰语', code: 'ga' },
    { name: '苏格兰盖尔语', code: 'gd' },
    { name: '加利西亚语', code: 'gl' },
    { name: '古吉拉特语', code: 'gu' },
    { name: '豪萨语', code: 'ha' },
    { name: '夏威夷语', code: 'haw' },
    { name: '希伯来语', code: 'he' },
    { name: '印地语', code: 'hi' },
    { name: '克罗地亚语', code: 'hr' },
    { name: '海地克里奥尔语', code: 'ht' },
    { name: '匈牙利语', code: 'hu' },
    { name: '亚美尼亚语', code: 'hy' },
    { name: '伊博语', code: 'ig' },
    { name: '冰岛语', code: 'is' },
    { name: '爪哇语', code: 'jw' },
    { name: '格鲁吉亚语', code: 'ka' },
    { name: '哈萨克语', code: 'kk' },
    { name: '高棉语', code: 'km' },
    { name: '卡纳达语', code: 'kn' },
    { name: '库尔德语', code: 'ku' },
    { name: '柯尔克孜语', code: 'ky' },
    { name: '拉丁语', code: 'la' },
    { name: '卢森堡语', code: 'lb' },
    { name: '老挝语', code: 'lo' },
    { name: '立陶宛语', code: 'lt' },
    { name: '拉脱维亚语', code: 'lv' },
    { name: '马尔加什语', code: 'mg' },
    { name: '毛利语', code: 'mi' },
    { name: '马其顿语', code: 'mk' },
    { name: '马拉雅拉姆语', code: 'ml' },
    { name: '蒙古语', code: 'mn' },
    { name: '马拉地语', code: 'mr' },
    { name: '马来语', code: 'ms' },
    { name: '马耳他语', code: 'mt' },
    { name: '白苗语', code: 'mww' },
    { name: '缅甸语', code: 'my' },
    { name: '尼泊尔语', code: 'ne' },
    { name: '荷兰语', code: 'nl' },
    { name: '挪威语', code: 'no' },
    { name: '齐切瓦语', code: 'ny' },
    { name: '克雷塔罗奥托米语', code: 'otq' },
    { name: '旁遮普语', code: 'pa' },
    { name: '波兰语', code: 'pl' },
    { name: '普什图语', code: 'ps' },
    { name: '罗马尼亚语', code: 'ro' },
    { name: '信德语', code: 'sd' },
    { name: '僧伽罗语', code: 'si' },
    { name: '斯洛伐克语', code: 'sk' },
    { name: '斯洛文尼亚语', code: 'sl' },
    { name: '萨摩亚语', code: 'sm' },
    { name: '修纳语', code: 'sn' },
    { name: '索马里语', code: 'so' },
    { name: '阿尔巴尼亚语', code: 'sq' },
    { name: '塞尔维亚语(西里尔文)', code: 'sr-Cyrl' },
    { name: '塞尔维亚语(拉丁文)', code: 'sr-Latn' },
    { name: '塞索托语', code: 'st' },
    { name: '巽他语', code: 'su' },
    { name: '瑞典语', code: 'sv' },
    { name: '斯瓦希里语', code: 'sw' },
    { name: '泰米尔语', code: 'ta' },
    { name: '泰卢固语', code: 'te' },
    { name: '塔吉克语', code: 'tg' },
    { name: '菲律宾语', code: 'tl' },
    { name: '克林贡语', code: 'tlh' },
    { name: '汤加语', code: 'to' },
    { name: '土耳其语', code: 'tr' },
    { name: '塔希提语', code: 'ty' },
    { name: '乌克兰语', code: 'uk' },
    { name: '乌尔都语', code: 'ur' },
    { name: '乌兹别克语', code: 'uz' },
    { name: '南非科萨语', code: 'xh' },
    { name: '意第绪语', code: 'yi' },
    { name: '约鲁巴语', code: 'yo' },
    { name: '尤卡坦玛雅语', code: 'yua' },
    { name: '粤语', code: 'yue' },
    { name: '南非祖鲁语', code: 'zu' }
  ],
  ali: [
    {name: '自动检测语言', code: 'auto'},
    {name: '英语', code: 'en'},
    {name: '中文', code: 'zh'},
    {name: '阿布哈兹语', code: 'ab'},
    {name: '阿尔巴尼亚语', code: 'sq'},
    {name: '阿肯语', code: 'ak'},
    {name: '阿拉伯语', code: 'ar'},
    {name: '阿拉贡语', code: 'an'},
    {name: '阿姆哈拉语', code: 'am'},
    {name: '阿萨姆语', code: 'as'},
    {name: '阿塞拜疆语', code: 'az'},
    {name: '阿斯图里亚斯语', code: 'ast'},
    {name: '阿兹特克语', code: 'nch'},
    {name: '埃维语', code: 'ee'},
    {name: '艾马拉语', code: 'ay'},
    {name: '爱尔兰语', code: 'ga'},
    {name: '爱沙尼亚语', code: 'et'},
    {name: '奥杰布瓦语', code: 'oj'},
    {name: '奥克语', code: 'oc'},
    {name: '奥里亚语', code: 'or'},
    {name: '奥罗莫语', code: 'om'},
    {name: '奥塞梯语', code: 'os'},
    {name: '巴布亚皮钦语', code: 'tpi'},
    {name: '巴什基尔语', code: 'ba'},
    {name: '巴斯克语', code: 'eu'},
    {name: '白俄罗斯语', code: 'be'},
    {name: '柏柏尔语', code: 'ber'},
    {name: '班巴拉语', code: 'bm'},
    {name: '邦阿西楠语', code: 'pag'},
    {name: '保加利亚语', code: 'bg'},
    {name: '北萨米语', code: 'se'},
    {name: '本巴语', code: 'bem'},
    {name: '比林语', code: 'byn'},
    {name: '比斯拉马语', code: 'bi'},
    {name: '俾路支语', code: 'bal'},
    {name: '冰岛语', code: 'is'},
    {name: '波兰语', code: 'pl'},
    {name: '波斯尼亚语', code: 'bs'},
    {name: '波斯语', code: 'fa'},
    {name: '博杰普尔语', code: 'bho'},
    {name: '布列塔尼语', code: 'br'},
    {name: '查莫罗语', code: 'ch'},
    {name: '查瓦卡诺语', code: 'cbk'},
    {name: '楚瓦什语', code: 'cv'},
    {name: '聪加语', code: 'ts'},
    {name: '鞑靼语', code: 'tt'},
    {name: '丹麦语', code: 'da'},
    {name: '掸语', code: 'shn'},
    {name: '德顿语', code: 'tet'},
    {name: '德语', code: 'de'},
    {name: '低地德语', code: 'nds'},
    {name: '低地苏格兰语', code: 'sco'},
    {name: '迪维西语', code: 'dv'},
    {name: '侗语', code: 'kdx'},
    {name: '杜順語', code: 'dtp'},
    {name: '俄语', code: 'ru'},
    {name: '法罗语', code: 'fo'},
    {name: '法语', code: 'fr'},
    {name: '梵语', code: 'sa'},
    {name: '菲律宾语', code: 'fil'},
    {name: '斐济语', code: 'fj'},
    {name: '芬兰语', code: 'fi'},
    {name: '弗留利语', code: 'fur'},
    {name: '富尔语', code: 'fvr'},
    {name: '刚果语', code: 'kg'},
    {name: '高棉语', code: 'km'},
    {name: '格雷罗纳瓦特尔语', code: 'ngu'},
    {name: '格陵兰语', code: 'kl'},
    {name: '格鲁吉亚语', code: 'ka'},
    {name: '格罗宁根方言', code: 'gos'},
    {name: '古吉拉特语', code: 'gu'},
    {name: '瓜拉尼语', code: 'gn'},
    {name: '哈萨克语', code: 'kk'},
    {name: '海地克里奥尔语', code: 'ht'},
    {name: '韩语', code: 'ko'},
    {name: '豪萨语', code: 'ha'},
    {name: '荷兰语', code: 'nl'},
    {name: '黑山语', code: 'cnr'},
    {name: '胡帕语', code: 'hup'},
    {name: '基里巴斯语', code: 'gil'},
    {name: '基隆迪语', code: 'rn'},
    {name: '基切语', code: 'quc'},
    {name: '吉尔吉斯斯坦语', code: 'ky'},
    {name: '加利西亚语', code: 'gl'},
    {name: '加泰罗尼亚语', code: 'ca'},
    {name: '捷克语', code: 'cs'},
    {name: '卡拜尔语', code: 'kab'},
    {name: '卡纳达语', code: 'kn'},
    {name: '卡努里语', code: 'kr'},
    {name: '卡舒比语', code: 'csb'},
    {name: '卡西语', code: 'kha'},
    {name: '康沃尔语', code: 'kw'},
    {name: '科萨语', code: 'xh'},
    {name: '科西嘉语', code: 'co'},
    {name: '克里克语', code: 'mus'},
    {name: '克里米亚鞑靼语', code: 'crh'},
    {name: '克林贡语', code: 'tlh'},
    {name: '克罗地亚语', code: 'hbs'},
    {name: '克丘亚语', code: 'qu'},
    {name: '克什米尔语', code: 'ks'},
    {name: '库尔德语', code: 'ku'},
    {name: '拉丁语', code: 'la'},
    {name: '拉特加莱语', code: 'ltg'},
    {name: '拉脱维亚语', code: 'lv'},
    {name: '老挝语', code: 'lo'},
    {name: '立陶宛语', code: 'lt'},
    {name: '林堡语', code: 'li'},
    {name: '林加拉语', code: 'ln'},
    {name: '卢干达语', code: 'lg'},
    {name: '卢森堡语', code: 'lb'},
    {name: '卢森尼亚语', code: 'rue'},
    {name: '卢旺达语', code: 'rw'},
    {name: '罗马尼亚语', code: 'ro'},
    {name: '罗曼什语', code: 'rm'},
    {name: '罗姆语', code: 'rom'},
    {name: '逻辑语', code: 'jbo'},
    {name: '马达加斯加语', code: 'mg'},
    {name: '马恩语', code: 'gv'},
    {name: '马耳他语', code: 'mt'},
    {name: '马拉地语', code: 'mr'},
    {name: '马拉雅拉姆语', code: 'ml'},
    {name: '马来语', code: 'ms'},
    {name: '马里语（俄罗斯）', code: 'chm'},
    {name: '马其顿语', code: 'mk'},
    {name: '马绍尔语', code: 'mh'},
    {name: '玛雅语', code: 'kek'},
    {name: '迈蒂利语', code: 'mai'},
    {name: '毛里求斯克里奥尔语', code: 'mfe'},
    {name: '毛利语', code: 'mi'},
    {name: '蒙古语', code: 'mn'},
    {name: '孟加拉语', code: 'bn'},
    {name: '缅甸语', code: 'my'},
    {name: '苗语', code: 'hmn'},
    {name: '姆班杜语', code: 'umb'},
    {name: '纳瓦霍语', code: 'nv'},
    {name: '南非语', code: 'af'},
    {name: '尼泊尔语', code: 'ne'},
    {name: '纽埃语', code: 'niu'},
    {name: '挪威语', code: 'no'},
    {name: '帕姆语', code: 'pmn'},
    {name: '帕皮阿门托语', code: 'pap'},
    {name: '旁遮普语', code: 'pa'},
    {name: '葡萄牙语', code: 'pt'},
    {name: '普什图语', code: 'ps'},
    {name: '齐切瓦语', code: 'ny'},
    {name: '契维语', code: 'tw'},
    {name: '切罗基语', code: 'chr'},
    {name: '日语', code: 'ja'},
    {name: '瑞典语', code: 'sv'},
    {name: '萨摩亚语', code: 'sm'},
    {name: '桑戈语', code: 'sg'},
    {name: '僧伽罗语', code: 'si'},
    {name: '上索布语', code: 'hsb'},
    {name: '世界语', code: 'eo'},
    {name: '斯洛文尼亚语', code: 'sl'},
    {name: '斯瓦希里语', code: 'sw'},
    {name: '索马里语', code: 'so'},
    {name: '斯洛伐克语', code: 'sk'},
    {name: '他加禄语', code: 'tl'},
    {name: '塔吉克语', code: 'tg'},
    {name: '塔希提语', code: 'ty'},
    {name: '泰卢固语', code: 'te'},
    {name: '泰米尔语', code: 'ta'},
    {name: '泰语', code: 'th'},
    {name: '汤加语（汤加群岛）', code: 'to'},
    {name: '汤加语（赞比亚）', code: 'toi'},
    {name: '提格雷尼亚语', code: 'ti'},
    {name: '图瓦卢语', code: 'tvl'},
    {name: '图瓦语', code: 'tyv'},
    {name: '土耳其语', code: 'tr'},
    {name: '土库曼语', code: 'tk'},
    {name: '瓦隆语', code: 'wa'},
    {name: '瓦瑞语（菲律宾）', code: 'war'},
    {name: '威尔士语', code: 'cy'},
    {name: '文达语', code: 've'},
    {name: '沃拉普克语', code: 'vo'},
    {name: '沃洛夫语', code: 'wo'},
    {name: '乌德穆尔特语', code: 'udm'},
    {name: '乌尔都语', code: 'ur'},
    {name: '乌孜别克语', code: 'uz'},
    {name: '西班牙语', code: 'es'},
    {name: '西方国际语', code: 'ie'},
    {name: '西弗里斯兰语', code: 'fy'},
    {name: '西里西亚语', code: 'szl'},
    {name: '希伯来语', code: 'he'},
    {name: '希利盖农语', code: 'hil'},
    {name: '夏威夷语', code: 'haw'},
    {name: '现代希腊语', code: 'el'},
    {name: '新共同语言', code: 'lfn'},
    {name: '信德语', code: 'sd'},
    {name: '匈牙利语', code: 'hu'},
    {name: '修纳语', code: 'sn'},
    {name: '宿务语', code: 'ceb'},
    {name: '叙利亚语', code: 'syr'},
    {name: '巽他语', code: 'su'},
    {name: '亚美尼亚语', code: 'hy'},
    {name: '亚齐语', code: 'ace'},
    {name: '伊班语', code: 'iba'},
    {name: '伊博语', code: 'ig'},
    {name: '伊多语', code: 'io'},
    {name: '伊洛卡诺语', code: 'ilo'},
    {name: '伊努克提图特语', code: 'iu'},
    {name: '意大利语', code: 'it'},
    {name: '意第绪语', code: 'yi'},
    {name: '因特语', code: 'ia'},
    {name: '印地语', code: 'hi'},
    {name: '印度尼西亚语', code: 'id'},
    {name: '印古什语', code: 'inh'},
    {name: '约鲁巴语', code: 'yo'},
    {name: '越南语', code: 'vi'},
    {name: '扎扎其语', code: 'zza'},
    {name: '爪哇语', code: 'jv'},
    {name: '中文繁体', code: 'zh-tw'},
    {name: '中文粤语', code: 'yue'},
    {name: '祖鲁语', code: 'zu'}
  ]
};